import { useEffect, useRef, useState } from 'react';
import { Users } from '@/hooks/user'
import { Auth } from '@/hooks/auth';
import Head from 'next/head';
import { Profile } from '@/interfaces/profile.interface';
import { Toast } from 'primereact/toast';
import Spinner from '../../components/spinner';


const Preferences = () => {
    const {setRoleUser} = Users();
    const {getUserAuthenticated} = Auth();

    const toast = useRef<Toast>(null);
    const [loading, setLoading] = useState<boolean>(false);

    const [user, setUser] = useState<Profile>(
        {
            uid:      0,
            email:    '',
            state:    false,
            name:     '',
            lastname: '',
            phone:    '',
            image:    '',
            role:     '',
            iat:      0,
            exp:      0,
        }
    );

    useEffect(() => {
        getUserAuthenticated(setUser);
    }, [])

    const setRole = async (e: any) => { 
        setLoading(true);
        let data = {
            role: 4
        };

        if(e.target.id == 'provider') {
            data.role = 3
        } else {
            data.role = 4;
        }

        await setRoleUser(user.uid, data, toast, setLoading);
    }

  return (
    <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <Spinner loading={loading} />
        <Toast ref={toast} />
        <div className='w-full h-screen bg-gray-100 flex flex-col items-center justify-center'>
            <div className='bg-white rounded-md shadow-lg flex flex-col items-center gap-20 justify-center p-10'>
                <div className='flex flex-row items-center gap-5'>
                    <img
                        src="https://images.squarespace-cdn.com/content/v1/634f43133040660154fd193a/07d993cf-6c35-46b4-a3d8-2c26c53b2958/Biggest_BoatMate-removebg-preview.png?format=1500w"
                        alt="logo"
                        className='w-16 lg:w-24'
                    />
                    <h1 className='mt-5 text-xl md:text-2xl font-semibold mr-5' style={{'color': '#373A85'}}>WHAT ROLE WOULD YOU LIKE TO FILL?</h1>
                </div>
                <div id='customer' onClick={setRole} className='w-full flex flex-row items-center justify-center gap-20'>
                    <div className='flex flex-col items-center gap-10 p-10 rounded-md shadow-md border hover:bg-green-100 cursor-pointer'>
                        <img id='customer' src="https://i.postimg.cc/Zn2fvXhV/sailor.png" alt="sailor" />
                        <p id='customer' className='font-extrabold text-[#373A85]'>BOAT OWNER</p>
                    </div>
                    <div id='provider' onClick={setRole} className='flex flex-col items-center gap-10 p-10 rounded-md shadow-md border hover:bg-green-100 cursor-pointer'>
                        <img id='provider' src="https://i.postimg.cc/L8h5v7Lm/cargo-ship.png" alt="provider" />
                        <p id='provider' className='font-extrabold text-[#373A85]'>PROVIDER</p>
                    </div>
                </div>
            </div>
        </div>
    </>
  )
}

export default Preferences