import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import MenuBar from './menuBar';
import FooterComponent from './footer';
import { Auth } from '@/hooks/auth';
import { Profile } from '@/interfaces/interfaces';
import { googleLogout } from '@react-oauth/google';

const LayoutPrincipal = ({children}: any) => {
    const {getUserAuthenticated, logout} = Auth();

    const [loading, setLoading] = useState<boolean>(false);

    const [user, setUser] = useState<Profile>();

    const getUser = async () => {
        try {
            const response = await getUserAuthenticated();
            if(response.status == 200) {
                setUser(response.data)
            }
        } catch (error) {
            return
        }
    }

    useEffect(() => {
        getUser();
    }, []);

    const logoutSession = async () => {
        googleLogout();
        logout(setLoading);
      };

    return (
        <>
            <Head>
                <title>BoatMate</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
            </Head>
            <MenuBar linkMenu='Join Our Pro Network' urlMenu='/pro' user={user} setLoading={setLoading} logout={logoutSession}/>
            <main className='w-full pt-10 md:pt-24 lg:pt-36'>
                {children}
            </main>
            <FooterComponent />
        </>
     );
}

export default LayoutPrincipal;