import React from 'react'
import Head from 'next/head'
import MenuBar from './menuBar';
import FooterProComponent from './footer_pro';
import FooterComponentThree from './footer-3';

const LayoutPro = ({children, footer}: any) => {
    return (
        <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <MenuBar linkMenu='Sign In' urlMenu='/login' menuItem={false}/>
         <main className={`w-full pt-10 md:pt-14 lg:pt-20 ${footer == 3 ? 'h-screen' : 'h-full'}`}>
            {children}
         </main>
         {
            footer == 1 ?
            <FooterProComponent />
            : footer == 2 ?
            <FooterComponentThree />
            : null
         }
        </>
     );
}

export default LayoutPro;