import React from 'react'
import Head from 'next/head'
import MenuBar from './menuBar';
import FooterComponent from './footer';

const LayoutPrincipal = ({children}: any) => {
    return (
        <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <MenuBar linkMenu='Join Our Pro Network' urlMenu='/pro'/>
         <main className='w-full pt-10 md:pt-24 lg:pt-36'>
            {children}
         </main>
         <FooterComponent />
        </>
     );
}

export default LayoutPrincipal;