import { Auth } from '@/hooks/auth';
import { googleLogout } from '@react-oauth/google'
import React, {useState, useEffect} from 'react'
import MenuBarSupAdmin from './menuBarSupAdmin';
import Head from 'next/head';
import SideBarComponent from './sideBar';
import FooterComponentAdmin from './footerAdmin';
import { Profile } from '@/interfaces/interfaces';
import {useContext} from 'react';
import { MenuContext } from '@/context/MenuContext';

const LayoutAdmin = ({children}: any) => {
   const {getUserAuthenticated, logout} = Auth();

   const {activeOption, setActiveOption, activeSideOption, setActiveSideOption} = useContext(MenuContext);

   const [loading, setLoading] = useState<boolean>(false);

   const [user, setUser] = useState<Profile>(
      {
          uid:                 0,
          email:               '',
          state:               false,
          google:               false,
          idPerson:            0,
          name:                '',
          lastname:            '',
          phone:               '',
          image:               '',
          idRole:              0,
          role:                '',
          idProvider:          0,
          providerName:        '',
          providerImage:       '',
          providerDescription: '',
          providerLat:         '',
          providerLng:         '',
          idCustomer:          '',
          customerLat:         '',
          customerLng:         '',
          iat:                 0,
          exp:                 0,
      }
  );

  useEffect(() => {
   setDataUser();
}, []);

  const setDataUser = async () => {
   const response = await getUserAuthenticated();
   setUser(response.data);
}

   const logoutSession = async () => {
      googleLogout();
      logout(setLoading);
  };

    return (
        <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <MenuBarSupAdmin
         user={user} setLoading={setLoading} logout={logoutSession} activeOption={activeOption} setActiveOption={setActiveOption} setActiveSideOption={setActiveSideOption}
        />
        <div className='w-full h-screen flex flex-row items-start justify-between gap-5 px-5 pb-5 pt-36 lg:pt-44 bg-neutral-100'>
            <SideBarComponent user={user} activeOption={activeOption} activeSideOption={activeSideOption} setActiveSideOption={setActiveSideOption} />
            <main className='w-full min-h-[360px] max-h-full h-full overflow-auto bg-white rounded-md shadow-md'>
               {children}
            </main>
        </div>
        <FooterComponentAdmin />
        </>
     );
}

export default LayoutAdmin;