import { Auth } from '@/hooks/auth';
import { googleLogout } from '@react-oauth/google'
import React, {useState, useEffect} from 'react'
import MenuBarSupAdmin from './menuBarSupAdmin';
import { Profile } from '@/interfaces/profile.interface';
import Head from 'next/head';
import SideBarComponent from './sideBar';
import Link from 'next/link';
import FooterComponentAdmin from './footerAdmin';

const LayoutAdmin = ({children, index, sideItem}: any) => {
   const {getUserAuthenticated, logout} = Auth();

   const [loading, setLoading] = useState<boolean>(false);

   const [user, setUser] = useState<Profile>(
      {
          uid:                 0,
          email:               '',
          state:               false,
          google:               false,
          idPerson:            0,
          name:                '',
          lastname:            '',
          phone:               '',
          image:               '',
          idRole:              0,
          role:                '',
          idProvider:          0,
          providerName:        '',
          providerImage:       '',
          zip:                 '',
          providerDescription: '',
          providerLat:         '',
          providerLng:         '',
          idCustomer:          '',
          customerLat:         '',
          customerLng:         '',
          iat:                 0,
          exp:                 0,
      }
  );

  useEffect(() => {
   setDataUser();
}, []);

  const setDataUser = async () => {
   const response = await getUserAuthenticated();
   setUser(response.data);
}

   const logoutSession = async () => {
      googleLogout()
      logout(setLoading)
  };

  const activeSideItem = (e: any) => {
      for (let i = 0; i < document.getElementsByClassName('side-item').length; i++) {
         document.getElementsByClassName('side-item').item(i)?.classList.remove('active-side-item')
      }
      document.getElementById(e.target.id)?.classList.add('active-side-item')
   };

   const activeSetSideItem = () => {
      for (let i = 0; i < document.getElementsByClassName('side-item').length; i++) {
          document.getElementsByClassName('side-item').item(i)?.classList.remove('active-side-item')
      }
      document.getElementsByClassName('side-item').item(0)?.classList.add('active-side-item')
   };

    return (
        <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <MenuBarSupAdmin 
        user={user} 
        index={index}
        logout={logoutSession} 
        setLoading={setLoading} 
        activeSetSideItem={activeSetSideItem} 
        />
        <div className='w-full h-screen flex flex-row items-start justify-between gap-5 px-5 pb-5 pt-36 lg:pt-44 bg-neutral-100'>
            <SideBarComponent index={index} sideItem={sideItem} activeSideItem={activeSideItem} />
            <main className='w-full min-h-[360px] max-h-full h-full overflow-auto bg-white rounded-md shadow-md'>
               {children}
            </main>
        </div>
        <FooterComponentAdmin />
        </>
     );
}

export default LayoutAdmin;