import Head from 'next/head'
import Layout from "@/components/layout";
import Principal from '@/pages/principal'

export default function Home() {
  return (
    <>
      <Head>
        <title>BoatMate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
      </Head>
      <Layout>
        <Principal></Principal>
      </Layout>
    </>
  )
}
