import { useEffect, useRef, useState } from 'react';
import { Users } from '@/hooks/user'
import { Auth } from '@/hooks/auth';
import Head from 'next/head';
import { Toast } from 'primereact/toast';
import Spinner from '../components/spinner';
import { Profile } from '@/interfaces/interfaces';


const Preferences = () => {
    const {setRoleUser} = Users();
    const {getUserAuthenticated} = Auth();

    const toast = useRef<Toast>(null);
    const [loading, setLoading] = useState<boolean>(false);

    const [user, setUser] = useState<Profile>(
        {
            uid:                 0,
            email:               '',
            state:               false,
            google:               false,
            idPerson:            0,
            name:                '',
            lastname:            '',
            phone:               '',
            image:               '',
            idRole:              0,
            role:                '',
            idProvider:          0,
            providerName:        '',
            providerImage:       '',
            providerDescription: '',
            providerLat:         '',
            providerLng:         '',
            idCustomer:          '',
            customerLat:         '',
            customerLng:         '',
            iat:                 0,
            exp:                 0,
        }
    );

    useEffect(() => {
        setDataUser();
    }, []);

    const setDataUser = async () => {
        const response = await getUserAuthenticated();
        setUser(response.data.user);
    }

    const setRole = async (e: any) => {
        setLoading(true);
        let data: any = {};

        if(e.target.id == 'provider') {
            data['role'] = 3
        } else {
            data['role'] = 4;
        }

        setRoleUser(user.uid, data, toast, setLoading);
    }

  return (
    <>
        <Head>
            <title>BoatMate</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" type="image/png" href="/Biggest_BoatMate-removebg-preview.ico" />
        </Head>
        <Spinner loading={loading} />
        <Toast ref={toast} />
        <div className='w-full h-screen bg-gray-100 flex flex-col items-center justify-center'>
            <h1 className='text-xl font-bold py-10'>Which best describes your role?</h1>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-10 items-center px-3 py-3">
                <div id='customer' className={`col-span-1 flex flex-col items-center gap-5 p-5 rounded-md shadow-lg shadow-gray-300/30 hover:shadow-sky-300/30 cursor-pointer border-none`} onClick={setRole}>
                    <div className='w-20 h-20 md:w-52 md:h-52 rounded-full overflow-hidden flex items-center justify-center'>
                        <img 
                        id='customer' 
                        src="https://s3-alpha-sig.figma.com/img/ddd5/77e1/14855842f8a56f007586b8285e9d0847?Expires=1693180800&Signature=dC2L0D7cgdZooQQFXKX8-waC2jEhK~cB-dzAhrE0XvrE0If7a~nu8hU9C8biDadeHKHWFrqa~ZNm1ZPQ9cmFUy5yBF4pgxX-udRrM5MpKMkH~R5H0-4xpLMuCT8AhaxCCFWpCBGK86ImEufpxOuViuyVVPJvP6Y4aZiH4W~Hr6~-ATyES1AF3srA~UAXbsv7vxW58lzzpZ4vssqY05F2JNhgCr3skEyzbvMA-ZpwTR6omtj36zfr1e7vrfH1Z~eTr0evMI1WhIv7z0usnJWiDd5BY5RkFCNkFLR~6qeyyuV-9NZ0lKmxT1Mc-P6nklT0LNTt0deY4KSsrzyxZq5LKQ__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4" 
                        alt="sailor"
                        className='w-full h-full object-cover' />
                    </div>
                    <p id='customer' className='font-extrabold'>CUSTOMER</p>
                </div>
                <div id='provider' className={`col-span-1 flex flex-col items-center gap-5 p-5 rounded-md shadow-lg shadow-gray-300/30 hover:shadow-sky-300/30 cursor-pointer border-none`} onClick={setRole}>
                    <div className='w-20 h-20 md:w-52 md:h-52 rounded-full overflow-hidden flex items-center justify-center'>
                        <img 
                        id='provider' 
                        src="https://s3-alpha-sig.figma.com/img/1a9a/fc2f/184b5b79b23f05c4cd45ec775514c43b?Expires=1693180800&Signature=dESmJYDeD8IZ3e2Eowj-xI2heHR7HZStGMvX6Af12wSKVnlFHJZkU4Ou7XO7wbLXE5-oORow020ZDMVnh-GpFP3A~79ht0VAH1dEDmskCrtCCfKyy9IfBMh5SHQPRyiN2m-tJ~A106~ScQw2dB~WRUmDZpgXXszxfy~z8~O6iDjASoJD03SQg03kdMo7zngZhppAYV-mLOo~c2qXDWoEwOPckixW0IdZVGgotKs1Y5PNLMrOAl1xa-8FJFEdyJtxB7aAlZor5USqIMBBvUCYkrWn8j86BugZuK5jR3FtUJ9r4mSzxmC5if-s2CudJ3UAUIk0XzJTzMr1PyO5QckIQg__&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4"
                        alt="provider"
                        className='w-full h-full object-cover' />
                    </div>
                    <p id='provider' className='font-extrabold'>PROVIDER</p>
                </div>
            </div>
            {/* <div className='bg-white md:rounded-md shadow-lg flex flex-col items-center gap-5 md:gap-20 justify-center p-10'>
                <div className='flex flex-row items-center gap-5'>
                    <img
                        src="https://images.squarespace-cdn.com/content/v1/634f43133040660154fd193a/07d993cf-6c35-46b4-a3d8-2c26c53b2958/Biggest_BoatMate-removebg-preview.png?format=1500w"
                        alt="logo"
                        className='w-16 lg:w-24'
                    />
                    <h1 className='text-center text-lg md:text-2xl font-semibold mr-5' style={{'color': '#373A85'}}>Which best describes your role?</h1>
                </div>
                <div id='customer' onClick={setRole} className='w-full flex flex-row items-center justify-between'>
                    <div className='flex flex-col items-center gap-5 md:gap-10 p-4 md:p-10 rounded-md shadow-md border hover:bg-green-100 cursor-pointer'>
                        <img id='customer' src="https://i.postimg.cc/Zn2fvXhV/sailor.png" width={100} height={100} alt="sailor" />
                        <p id='customer' className='font-extrabold text-[#373A85]'>BOAT OWNER</p>
                    </div>
                    <div id='provider' onClick={setRole} className='flex flex-col items-center gap-5 md:gap-10 p-4 md:p-10 rounded-md shadow-md border hover:bg-green-100 cursor-pointer'>
                        <img id='provider' src="https://i.postimg.cc/L8h5v7Lm/cargo-ship.png" width={100} height={100} alt="provider" />
                        <p id='provider' className='font-extrabold text-[#373A85]'>PROVIDER</p>
                    </div>
                </div>
            </div> */}
        </div>
    </>
  )
}

export default Preferences